### PR TITLE
Disable autosave

### PR DESCRIPTION
**Pull request by a-b-r-o-w-n**
Our team collectively dislikes this feature. We have a watch that runs our test on every change and this becomes troublesome with autosave.

If this is generally liked, then we need a way to have project specific config

### CODE REVIEW

**Comment by aaronjensen** [comment]
I like it, but I too am annoyed by watch+autosave. FWIW, I think a better (but more challenging) change would be to have the tests run more quickly and only runs specifically affected tests. Karma + webpack sucks though...

**Comment by radamant** [comment]
I like this too

**Comment by aaronjensen** [comment]
you like autosave or disabling it?

**Comment by radamant** [comment]
I like disabling it

**Comment by aaronjensen** [comment]
Cool, let's do it then!

**Pull request merged**
