### PR TITLE
Add quick-file-actions

### PR DESCRIPTION
**Pull request by aaronjensen**

### CODE REVIEW

**Comment by a-b-r-o-w-n** [comment]
I think tree view already exposes these functions. We could just use those for the key bindings.

**Comment by aaronjensen** [comment]
@astephenb i'm not sure I follow. Tree view's bindings are specific to tree view and wouldn't work anywhere else (things like M, or cmd-c).

**Comment by a-b-r-o-w-n** [comment]
screen shot 2015-07-31 at 11 53 02 am
you can access these from the command window.

**Comment by aaronjensen** [comment]
oh i got ya, we don't need the extra package. cool, good idea, thanks.

**Comment by aaronjensen** [comment]
@astephenb how's that look?

**Comment by a-b-r-o-w-n** [comment]
:+1:

**Pull request merged**
