### PR TITLE
Add some options to advanced new file

### PR DESCRIPTION
**Pull request by a-b-r-o-w-n**
screen shot 2015-07-13 at 9 56 51 am

### CODE REVIEW

**Comment by a-b-r-o-w-n** [comment]
Not sure what people think about this. I like it to give me context.

**Comment by aaronjensen** [comment]
those look good to me. are there similar options for open? specifically the show current file

**Comment by a-b-r-o-w-n** [comment]
@aaronjensen it doesn't look like there is.

**Comment by aaronjensen** [comment]
too bad, :shipit:

**Pull request merged**
