### PR TITLE
add project-find-navigation

### PR DESCRIPTION
**Pull request by aaronjensen**
There's no built in way to navigate "find in project" with the keyboard. This adds a way.

### CODE REVIEW

**Comment by aaronjensen** [comment]
project-find-navigation

**Comment by radamant** [comment]
@aaronjensen looks like there are some conflicts that need to be dealt with before merge

**Comment by aaronjensen** [comment]
yea, i don't like backmerges, so i tend to fix the conflicts on the merge in, but i can merge back here.

**Comment by aaronjensen** [comment]
all bettah @radamant

**Pull request merged**
