### PR TITLE
add set-syntax package, bump package versions

### PR DESCRIPTION
**Pull request by a-b-r-o-w-n**
This just adds a command to set syntax for a file without having to click the syntax link at the bottom of the editor.

### CODE REVIEW

**Comment by aaronjensen** [comment]
Cool, can you update the readme? Then all good

**Comment by a-b-r-o-w-n** [comment]
Not really sure what to put in there. There are no keyboard bindings or anything, just a command in the command palette

**Comment by aaronjensen** [comment]
a reference in https://github.com/substantial/atomfiles#installed

**Comment by a-b-r-o-w-n** [comment]
Done.

**Pull request merged**
