### PR TITLE
Add linter and eslint

### PR DESCRIPTION
**Pull request by aaronjensen**

### CODE REVIEW

**Comment by aaronjensen** [comment]
Pretty nasty pull request when adding packages. Just these two packages alone are 27M or so.

**Comment by amay** [comment]
yikes... I didn't realize just how big these were going to be. hm...

`apm help install` specifies that we can use a version in the packages.txt file, so that would solve the version issue. We could also explicitly whitelist the packages we expect under the ./packages dir which would allow us to see new packages as dirty in local git. I think that addresses the second concern you had with the packages.txt approach. It is definitely a little weird to edit the .gitignore when adding a new package, but not terrible.

Also, if we go the `curl | sh` route for installing, we can automate the package install so we don't have to worry about command line issues.

**Comment by aaronjensen** [comment]
yeah. I think that's probably going to be the best approach. It turns out `apm` can write exactly what we want, w/ versions:

``` bash
apm list --installed --bare > packages.txt
```

There are plugins that handle it too, but they aren't very mature. I think if we script this and eventually build our own package around it it would work great. 

One downside is it currently installs every package even if it's already installed. We can script around that though.

**Comment by aaronjensen** [comment]
i'ma kill this one in favor of some sort of script. I don't think this is great.

**Pull request closed without merging**
