### PR TITLE
Remove emacs cancel binding

### PR DESCRIPTION
**Pull request by a-b-r-o-w-n**
This overwrites a core binding (go to line).

### CODE REVIEW

**Comment by aaronjensen** [comment]
oops, my bad.

If we want, we can do this:

```
'.platform-darwin atom-text-editor.lazy-motion':
  'ctrl-g': 'core:cancel'
```

that'll scope it to within lazy-motion itself

**Comment by radamant** [comment]
I'd vote to either leave this in, or find some other home-row option for cancel (as control-[ does not appear to work as escape in atom)

**Comment by aaronjensen** [comment]
ctrl-[ works for me, but i may have that w/ karabiner. We could add ctrl-[. 

I'm somewhat ambivalent on this. I think we should have a goto line binding and a home row escape. ctrl-g is a default so that seems to edge out imo.

**Comment by a-b-r-o-w-n** [comment]
I scoped it to lazy motion. Is this good to merge?

**Comment by aaronjensen** [comment]
looks good :shipit:

**Pull request merged**
