### PR TITLE
Add bindings for vim-like * and #

### PR DESCRIPTION
**Pull request by aaronjensen**

### CODE REVIEW

**Comment by radamant** [comment]
It would be nice if these shortcuts could be related to find-next and find-previous shortcuts, for example if find-next is ctrl-s, find-next-current-word could be ctrl-shift-s or ctrl-opt-s. I know there's a tricky dance with trying to avoid pre-existing shortcuts, but I personally like having similar functionality using similar shortcuts but with modifiers like cmd,opt,shift.

**Comment by aaronjensen** [comment]
ctrl-opt is a particularly nasty combination on most keyboards so I'm trying to avoid it. Find next/prev are cmd-g/cmd-shift-g, so they're already consumed. alt-g is the git/github leader key, ctrl-g is go to line.

The current bindings are catering to vim muscle memory of `*`/`#`. I'm open to other suggestions, but I'm not sure how to relate it to find next/prev.

It'd be nice if we had a list of available bindings.....

**Comment by radamant** [comment]
I prefer lazy-motion for find next/previous. That's currently opt-s/opt-r, which kills my thumbs and I liked it better as ctrl-s and ctrl-r. So in my ideal scenario, ctrl-s would be search-forward and ctrl-shift-s would be search-forward-current-word and find-till would be moved to opt-s/r

**Comment by aaronjensen** [comment]
Gotcha. I was split on the opt/ctrl bit for lazy-motion. alt-shift-s is some available snippet menu which seems like it's probably not used by many. I'm hesitant to kill that one, but it's not a super important/common one.

re: alt, I know you don't want to be a fancy pants, but it's pretty nice to remap right cmd to opt and it's really easy w/ [Karabiner](https://github.com/tekezo/Karabiner).

I wouldn't mind moving find/till to a mod of f/b but there aren't many free... ctrl-cmd-f opens up some facebook bullshit on osx

**Comment by aaronjensen** [comment]
oh snap that was pandabar. But now that it's free, ctrl-cmd-f is full screen.. sigh

**Comment by radamant** [comment]
le sigh :panda_face:

**Comment by aaronjensen** [comment]
I'ma merge this for now, but I'm open to moving things around if anyone has ideas.

**Pull request merged**
